# 観測地点の設定
location:
  latitude: 35.0153
  longitude: 138.5187
  
  
# 計算対象の日付 (YYYY-MM-DD形式)
target:
  date: "2025-12-22"

# 計算設定（通常は変更不要）
settings:
  check_distance_km: 20   # 何km先の山まで考慮するか
  step_minutes: 1        # 何分刻みで計算するか（小さいほど高精度だが遅い）